version: '3.12'
services:
  web:
    image: ghcr.io/kaushalacts/django-hello-k8s:latest
    ports:
      - "8001:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=myproject.settings.development
      - DEBUG=True
    restart: always